name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_CORE: ${{ github.repository }}-core
  IMAGE_NAME_PERIPHERY: ${{ github.repository }}-periphery

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Core
      id: meta-core
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_CORE }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Extract metadata for Periphery
      id: meta-periphery
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PERIPHERY }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Core Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./bin/core/aio.Dockerfile
        push: true
        tags: ${{ steps.meta-core.outputs.tags }}
        labels: ${{ steps.meta-core.outputs.labels }}

    - name: Build and push Periphery Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./bin/periphery/aio.Dockerfile
        push: true
        tags: ${{ steps.meta-periphery.outputs.tags }}
        labels: ${{ steps.meta-periphery.outputs.labels }}